name: CI
on: pull_request

jobs:
  Test:
    runs-on:
      - self-hosted
      - CI-CD

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Run actionlint
        run: actionlint -ignore 'label "CI-CD" is unknown' .github/workflows/CI.yml

      - name: Run codespell
        run: codespell --enable-colors

      - name: Run mdl
        run: mdl --style .github/workflows/mdl_style.rb .

      - name: Run shellcheck
        run: find . -name '*.sh' -exec shellcheck --color=always {} +

      - name: Run hadolint
        run: docker run --rm -i hadolint/hadolint --ignore DL4006 < Dockerfile

      - name: Cleanup docker images
        run: docker image prune -af
